proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
    url: http://localhost:2375
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo

  - id: rstudio1
    displayName: RStudio
    description: A RStudio server that is never terminated by ShinyProxy
    containerImage: openanalytics/shinyproxy-rstudio-ide-demo:1.4.1106__4.0.4
    port: 8787
    container-env:
      DISABLE_AUTH: true
      WWW_ROOT_PATH: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}" 
    heartbeat-timeout: -1
    stop-on-logout: false
    max-lifetime: -1

  - id: rstudio2
    displayName: RStudio
    description: A RStudio server that is only terminated after 24 hours
    containerImage: openanalytics/shinyproxy-rstudio-ide-demo:1.4.1106__4.0.4
    port: 8787
    container-env:
      DISABLE_AUTH: true
      WWW_ROOT_PATH: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}" 
    heartbeat-timeout: -1
    stop-on-logout: false
    max-lifetime: 2

  - id: rstudio3
    displayName: RStudio
    containerImage: openanalytics/shinyproxy-rstudio-ide-demo:1.4.1106__4.0.4
    description: A RStudio server that is only terminated when the user logs out
    port: 8787
    container-env:
      DISABLE_AUTH: true
      WWW_ROOT_PATH: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}" 
    heartbeat-timeout: -1
    stop-on-logout: true
    max-lifetime: -1

  stop-proxies-on-shutdown: false
  recover-running-proxies: true

logging:
  file:
    namw: shinyproxy.log
